# Site settings
title: Yunhe's blog
email: yunheyj@outlook.com
description: "Musing on Game,AI, CG! "
baseurl: ""
url: "http://yunhenk.github.io"
twitter_username: yunhenk
github_username:  yunhenk

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
